sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  txcos:
    secret-id: AKIDY0QqJrR0VsEc6czJmTApHnJfnpgLqEUb
    secret-key: 0oPsAHBsOkogJisnV2PalqkalnlY8eOD
    region: ap-beijing
    bucket-name: sky-1306474759
